import type { Badge, StudentProfile } from "./types";

const daysAgo = (d: number) => new Date(Date.now() - d * 86_400_000).toISOString();

export const MOCK_PROFILE: StudentProfile = {
  name: "Orlando Fortuna",
  handle: "@orlandofortuna",
  university: "Universidade Agostinho Neto (UAN)",
  course: "Engenharia Informática",
  year: "4.º ano",
  bio: "Foco em engenharia de software, estruturas de dados e algoritmos. Mais de 120 quizzes concluídos.",
  plan: "pro",
  verified: true,
  accuracy: 89.4,
  answered: 450,
  league: "Divisão Ouro na liga da UAN",
  counts: { cadeiras: 4, sebentas: 12, badges: 8 },
  activity: [
    {
      id: "a1",
      icon: "chart",
      title: "Estruturas de dados avançadas",
      detail: "Árvores binárias de busca e balanceamento AVL",
      at: daysAgo(1),
      score: "10/10",
      xp: 50,
      href: "/v2/leitura",
    },
    {
      id: "a2",
      icon: "cpu",
      title: "Engenharia de software II",
      detail: "Padrões de desenho",
      at: daysAgo(3),
      score: "9/10",
      xp: 40,
      href: "/v2/leitura",
    },
    {
      id: "a3",
      icon: "file",
      title: "Bases de dados II",
      detail: "Normalização e transações ACID",
      at: daysAgo(5),
      score: "10/10",
      xp: 60,
      href: "/v2/leitura",
    },
  ],
  saved: [
    { id: "s1", title: "Sebenta de política cambial", subject: "Macroeconomia I", sizeKb: 320, offline: true, href: "/v2/sebenta" },
    { id: "s2", title: "Algoritmos em Python: da teoria ao exame", subject: "Programação I", sizeKb: 480, offline: true, href: "/v2/sebenta" },
    { id: "s3", title: "Contabilidade Geral I: lançamentos e PGC", subject: "Contabilidade", sizeKb: 260, offline: false, href: "/v2/sebenta" },
  ],
  exams: [
    { id: "e1", title: "Simulado de Estruturas de Dados", at: daysAgo(2), accuracy: 90, minutes: 12, href: "/v2/desafio" },
    { id: "e2", title: "Desafio relâmpago: macroeconomia", at: daysAgo(6), accuracy: 70, minutes: 5, href: "/v2/desafio" },
  ],
};

export const BADGES: Badge[] = [
  {
    id: "caloiro",
    name: "Caloiro Kombinu 2026",
    description: "Concluiu o onboarding e escolheu a cadeira crítica.",
    category: "cadeiras",
    icon: "school",
    unlockedAt: "2026-08-12",
    proof: "uan-0x4a9",
  },
  {
    id: "moeda",
    name: "Mestre da moeda",
    description: "100% de acertos nos quizzes de Macroeconomia I.",
    category: "quizzes",
    icon: "target",
    unlockedAt: "2026-08-24",
    proof: "uan-0x81b",
  },
  {
    id: "lean",
    name: "Sentinela data-lean",
    description: "Mais de 20 horas de estudo abaixo de 3,5 MB/h.",
    category: "streaks",
    icon: "signal",
    unlockedAt: "2026-08-28",
    proof: "uan-0x2f7",
  },
  {
    id: "top1",
    name: "Top 1% da faculdade",
    description: "Chegou à Divisão Ouro da liga da UAN.",
    category: "comunidade",
    icon: "trophy",
    unlockedAt: "2026-09-02",
    proof: "uan-0x903",
  },
  {
    id: "streak30",
    name: "Ofensiva de 30 dias",
    description: "Estuda 30 dias seguidos sem falhar a meta diária.",
    category: "streaks",
    icon: "flame",
    progress: { value: 14, goal: 30, unit: "dias" },
  },
  {
    id: "maratona",
    name: "Maratona de simulados",
    description: "Concluir 10 simulados completos num semestre.",
    category: "quizzes",
    icon: "bolt",
    progress: { value: 6, goal: 10, unit: "simulados" },
  },
  {
    id: "mentor",
    name: "Mentor de turma",
    description: "Responder a 25 dúvidas de colegas na tua cadeira.",
    category: "comunidade",
    icon: "users",
    progress: { value: 9, goal: 25, unit: "respostas" },
  },
  {
    id: "critica",
    name: "Cadeira dominada",
    description: "Terminar todos os módulos de uma cadeira crítica.",
    category: "cadeiras",
    icon: "book",
    progress: { value: 6, goal: 7, unit: "módulos" },
  },
];
