import type { CreatorMaterial } from "./types";

const daysAgo = (d: number) => new Date(Date.now() - d * 86_400_000).toISOString();

export const CREATOR_MATERIALS: CreatorMaterial[] = [
  {
    id: "m-macro",
    title: "Manual de exercícios: Macroeconomia I",
    subject: "Economia",
    university: "UAN",
    year: "2.º ano",
    pages: 45,
    quizzes: 15,
    sizeKb: 1434,
    priceKz: 1500,
    visibility: "publico",
    sales: 94,
    rating: 4.9,
    reviews: 42,
    status: "publicado",
    updatedAt: daysAgo(4),
    studioHref: "/v2/estudio",
  },
  {
    id: "m-cambio",
    title: "Sebenta teórica: modelo IS-LM e câmbio",
    subject: "Macroeconomia II",
    university: "UAN",
    year: "3.º ano",
    pages: 28,
    quizzes: 15,
    sizeKb: 980,
    priceKz: 2000,
    visibility: "publico",
    sales: 31,
    rating: 4.7,
    reviews: 18,
    status: "publicado",
    updatedAt: daysAgo(12),
    studioHref: "/v2/estudio",
  },
  {
    id: "m-estatistica",
    title: "Pack de quizzes: Estatística I",
    subject: "Estatística",
    university: "ISAF",
    year: "1.º ano",
    pages: 12,
    quizzes: 30,
    sizeKb: 420,
    priceKz: 0,
    visibility: "publico",
    sales: 210,
    rating: 4.8,
    reviews: 57,
    status: "publicado",
    updatedAt: daysAgo(20),
    studioHref: "/v2/estudio",
  },
  {
    id: "m-simulado",
    title: "Simulado: exame da Ordem (época especial)",
    subject: "Direito",
    university: "UCAN",
    year: "5.º ano",
    pages: 36,
    quizzes: 40,
    sizeKb: 1760,
    priceKz: 4500,
    visibility: "link",
    sales: 17,
    rating: 5,
    reviews: 9,
    status: "pausado",
    updatedAt: daysAgo(31),
    studioHref: "/v2/estudio",
  },
  {
    id: "m-financas",
    title: "Finanças públicas: notas de revisão",
    subject: "Finanças Públicas",
    university: "ISAF",
    year: "3.º ano",
    pages: 22,
    quizzes: 8,
    sizeKb: 640,
    priceKz: 1000,
    visibility: "faculdade",
    sales: 0,
    rating: null,
    reviews: 0,
    status: "em-moderacao",
    updatedAt: daysAgo(1),
    studioHref: "/v2/estudio",
  },
  {
    id: "m-draft",
    title: "Introdução à escassez (rascunho)",
    subject: "Economia I",
    university: "UAN",
    year: "1.º ano",
    pages: 6,
    quizzes: 1,
    sizeKb: 120,
    priceKz: 0,
    visibility: "publico",
    sales: 0,
    rating: null,
    reviews: 0,
    status: "rascunho",
    updatedAt: daysAgo(0),
    studioHref: "/v2/estudio",
  },
];
