import type { SearchResults } from "./types";

export const MOCK_SEARCH: SearchResults = {
  query: "macroeconomia uan",
  best: {
    subject: "Macroeconomia I",
    university: "UAN",
    faculty: "Faculdade de Economia",
    year: "2.º ano",
    semester: "1.º semestre",
    materials: 18,
    students: 140,
    href: "/v2/trilha",
  },
  hits: [
    {
      id: "s1",
      kind: "sebenta",
      title: "Sebenta teórica: modelo IS-LM e balanço de pagamentos",
      subtitle: "Mateus Silva · docente verificado",
      university: "UAN",
      year: "2.º ano",
      priceKz: 1500,
      rating: 4.9,
      reviews: 42,
      sizeKb: 1434,
      verified: true,
      href: "/v2/sebenta",
    },
    {
      id: "s2",
      kind: "sebenta",
      title: "Guia de fórmulas e exercícios de macroeconomia angolana",
      subtitle: "Hamilton Kiala · explicador homologado",
      university: "UCAN",
      year: "2.º ano",
      priceKz: 0,
      rating: 4.8,
      reviews: 29,
      sizeKb: 850,
      verified: true,
      href: "/v2/sebenta",
    },
    {
      id: "s3",
      kind: "sebenta",
      title: "Resumo rápido: política monetária do BNA",
      subtitle: "Célia Ngola · assistente universitária",
      university: "UAN",
      year: "3.º ano",
      priceKz: 1000,
      rating: 4.6,
      reviews: 18,
      sizeKb: 420,
      href: "/v2/sebenta",
    },
    {
      id: "q1",
      kind: "simulado",
      title: "Simulado do exame final de Macroeconomia I",
      subtitle: "20 questões calibradas pelos exames dos últimos 3 anos",
      university: "UAN",
      minutes: 15,
      xp: 60,
      attempts: 890,
      href: "/v2/desafio",
    },
    {
      id: "q2",
      kind: "simulado",
      title: "Checkpoints de balanço de pagamentos",
      subtitle: "12 questões com explicação de cada alternativa",
      university: "UAN",
      minutes: 8,
      xp: 35,
      attempts: 410,
      href: "/v2/desafio",
    },
    {
      id: "e1",
      kind: "explicador",
      title: "Mateus Silva",
      subtitle: "Macroeconomia I e II · Faculdade de Economia",
      university: "UAN",
      rating: 4.95,
      reviews: 142,
      verified: true,
      href: "/v2/criador",
    },
    {
      id: "e2",
      kind: "explicador",
      title: "Teresa Bento",
      subtitle: "Cátedra de Macroeconomia · 8 materiais publicados",
      university: "UAN",
      rating: 4.9,
      reviews: 96,
      verified: true,
      href: "/v2/criador",
    },
    {
      id: "c1",
      kind: "cadeira",
      title: "Macroeconomia II",
      subtitle: "Plano curricular ativo · 11 materiais validados",
      university: "UAN",
      year: "3.º ano",
      href: "/v2/cadeira",
    },
  ],
};
