import type { ImportedRow, Question, Topic, VersionEntry } from "./types";

const daysAgo = (d: number) => new Date(Date.now() - d * 86_400_000).toISOString();

export const TOPICS: Topic[] = [
  { id: "t-cambial", name: "Mercado cambial e reservas", subjectId: "macro1", examWeight: 25 },
  { id: "t-islm", name: "Modelo IS-LM", subjectId: "macro1", examWeight: 30 },
  { id: "t-mundell", name: "Mundell-Fleming", subjectId: "macro1", examWeight: 25 },
  { id: "t-bna", name: "Política monetária do BNA", subjectId: "macro1", examWeight: 20 },
];

export const QUESTIONS: Question[] = [
  {
    id: "q-001",
    type: "escolha",
    stem: "Com câmbio fixo e mobilidade perfeita de capitais, qual é o efeito de uma política monetária expansionista sobre o produto?",
    options: [
      { id: "a", label: "A", text: "O produto aumenta de forma permanente.", explanation: "O aumento inicial é anulado: para defender a paridade, o banco central vende divisas e retira a liquidez que emitiu.", share: 18 },
      { id: "b", label: "B", text: "O produto não se altera: há drenagem de reservas.", explanation: "Certo. Com câmbio fixo e capitais móveis, a política monetária perde eficácia sobre o produto.", share: 38 },
      { id: "c", label: "C", text: "O produto cai por causa da subida da taxa de juro.", explanation: "A taxa de juro volta ao nível internacional por arbitragem; não sobe acima dele.", share: 31 },
      { id: "d", label: "D", text: "O efeito depende apenas da política fiscal.", explanation: "A política fiscal é eficaz neste regime, mas a pergunta é sobre a monetária.", share: 13 },
    ],
    correctOptionId: "b",
    topicIds: ["t-mundell"],
    declaredDifficulty: 3,
    estimatedSeconds: 75,
    observed: { answers: 184, accuracy: 38 },
    usedIn: 3,
    updatedAt: daysAgo(2),
  },
  {
    id: "q-002",
    type: "escolha",
    stem: "As remessas de emigrantes entram em que conta do balanço de pagamentos?",
    options: [
      { id: "a", label: "A", text: "Conta corrente, no rendimento secundário.", explanation: "Certo. São transferências correntes sem contrapartida.", share: 61 },
      { id: "b", label: "B", text: "Conta de capital.", explanation: "A conta de capital regista transferências de capital, como perdões de dívida.", share: 28 },
      { id: "c", label: "C", text: "Conta financeira.", explanation: "A conta financeira regista ativos e passivos externos, não rendimentos.", share: 11 },
    ],
    correctOptionId: "a",
    topicIds: ["t-cambial"],
    declaredDifficulty: 1,
    estimatedSeconds: 45,
    observed: { answers: 212, accuracy: 61 },
    usedIn: 2,
    updatedAt: daysAgo(6),
  },
  {
    id: "q-003",
    type: "vf",
    stem: "Uma subida do coeficiente de reservas obrigatórias aumenta a liquidez livre dos bancos comerciais.",
    options: [
      { id: "v", label: "V", text: "Verdadeiro", explanation: "Reservas obrigatórias mais altas retêm fundos no banco central e reduzem a liquidez livre.", share: 22 },
      { id: "f", label: "F", text: "Falso", explanation: "Certo: o efeito é o inverso, menos liquidez e menos crédito disponível.", share: 78 },
    ],
    correctOptionId: "f",
    topicIds: ["t-bna"],
    declaredDifficulty: 1,
    estimatedSeconds: 30,
    observed: { answers: 198, accuracy: 78 },
    usedIn: 4,
    updatedAt: daysAgo(9),
  },
  {
    id: "q-004",
    type: "numerico",
    stem: "Créditos de 4.950.000 Kz e débitos de 3.750.000 Kz. Qual é o saldo da conta corrente, em Kwanzas?",
    options: [{ id: "n", label: "=", text: "1200000", explanation: "Créditos menos débitos: 4.950.000 − 3.750.000 = 1.200.000 Kz." }],
    correctOptionId: "n",
    topicIds: ["t-cambial"],
    declaredDifficulty: 2,
    estimatedSeconds: 90,
    usedIn: 1,
    updatedAt: daysAgo(1),
  },
  {
    id: "q-005",
    type: "escolha",
    stem: "No modelo IS-LM, o que desloca a curva IS para a direita?",
    options: [
      { id: "a", label: "A", text: "Aumento dos gastos públicos.", explanation: "Certo. Mais despesa eleva a procura agregada para cada nível de taxa de juro.", share: 54 },
      { id: "b", label: "B", text: "Aumento da oferta de moeda.", explanation: "Isso desloca a LM, não a IS.", share: 29 },
      { id: "c", label: "C", text: "Subida da taxa de juro.", explanation: "A taxa de juro move-se ao longo da IS; não a desloca.", share: 17 },
    ],
    correctOptionId: "a",
    topicIds: ["t-islm"],
    declaredDifficulty: 2,
    estimatedSeconds: 60,
    observed: { answers: 156, accuracy: 54 },
    usedIn: 2,
    updatedAt: daysAgo(14),
  },
  {
    id: "q-006",
    type: "escolha",
    stem: "Numa economia aberta com câmbio flutuante, a política fiscal expansionista perde eficácia porque:",
    options: [
      { id: "a", label: "A", text: "A moeda aprecia e as exportações líquidas caem.", explanation: "Certo. A entrada de capitais aprecia o Kwanza e reduz as exportações líquidas.", share: 47 },
      { id: "b", label: "B", text: "A oferta de moeda cai automaticamente.", explanation: "Com câmbio flutuante o banco central não é obrigado a intervir.", share: 33 },
      { id: "c", label: "C", text: "Os preços sobem de imediato.", explanation: "O canal relevante aqui é o cambial, não o de preços de curto prazo.", share: 20 },
    ],
    correctOptionId: "a",
    topicIds: ["t-mundell", "t-islm"],
    declaredDifficulty: 3,
    estimatedSeconds: 80,
    observed: { answers: 142, accuracy: 47 },
    usedIn: 1,
    updatedAt: daysAgo(20),
  },
];

export const VERSIONS: VersionEntry[] = [
  {
    id: "v13",
    label: "Versão 1.3",
    status: "rascunho",
    at: daysAgo(0),
    author: "Mateus Silva",
    summary: "Correção do gabarito do checkpoint 4 e reescrita do módulo 2.",
    readersOnVersion: 0,
    changes: [
      { kind: "alterado", text: "Checkpoint 4: gabarito corrigido de C para B, com explicação por alternativa." },
      { kind: "adicionado", text: "Módulo 2: exemplo resolvido antes da teoria." },
    ],
  },
  {
    id: "v12",
    label: "Versão 1.2",
    status: "publicada",
    at: daysAgo(12),
    author: "Mateus Silva",
    summary: "Novo diagrama de transmissão cambial e dois checkpoints.",
    readersOnVersion: 83,
    changes: [
      { kind: "adicionado", text: "Diagrama 2.1 de transmissão cambial." },
      { kind: "adicionado", text: "Dois checkpoints no módulo 3." },
      { kind: "removido", text: "Parágrafo repetido na introdução." },
    ],
  },
  {
    id: "v11",
    label: "Versão 1.1",
    status: "arquivada",
    at: daysAgo(46),
    author: "Mateus Silva",
    summary: "Primeira revisão depois da moderação.",
    readersOnVersion: 11,
    changes: [{ kind: "alterado", text: "Linguagem simplificada no módulo 1, a pedido da moderação." }],
  },
];

export const IMPORTED_ROWS: ImportedRow[] = [
  {
    id: "r1",
    line: 3,
    stem: "Qual é o principal instrumento de política monetária do BNA?",
    options: ["Taxa básica de juro", "Imposto industrial", "Salário mínimo", "Pauta aduaneira"],
    correctIndex: 0,
    topicId: "t-bna",
    issues: [],
  },
  {
    id: "r2",
    line: 7,
    stem: "A depreciação do Kwanza encarece as importações.",
    options: ["Verdadeiro", "Falso"],
    correctIndex: 0,
    topicId: "t-cambial",
    issues: [],
  },
  {
    id: "r3",
    line: 11,
    stem: "O que acontece à curva LM quando a oferta de moeda aumenta?",
    options: ["Desloca-se para a direita", "Desloca-se para a esquerda", "Não se altera"],
    correctIndex: null,
    topicId: "t-islm",
    issues: [{ field: "gabarito", message: "O ficheiro não indica qual é a resposta certa." }],
  },
  {
    id: "r4",
    line: 15,
    stem: "Define reservas internacionais líquidas.",
    options: [],
    correctIndex: null,
    topicId: null,
    issues: [
      { field: "alternativas", message: "Sem alternativas: perguntas abertas ainda não são suportadas." },
      { field: "topico", message: "Sem tópico atribuído." },
    ],
  },
  {
    id: "r5",
    line: 19,
    stem: "Com câmbio fixo, a política fiscal é eficaz para alterar o produto.",
    options: ["Verdadeiro", "Falso"],
    correctIndex: 0,
    topicId: null,
    issues: [{ field: "topico", message: "Sem tópico atribuído." }],
  },
];
