import type { AdaptiveTrail, LearningTrail } from "./types";

export const MOCK_TRAIL: LearningTrail = {
  subject: "Macroeconomia I",
  headline: "Teoria monetária e câmbio",
  year: "3.º ano",
  semester: "1.º semestre",
  finalExam: { title: "Exame simulado da cadeira", minutes: 45, xp: 200, href: "/v2/desafio" },
  nodes: [
    {
      id: "n1",
      order: 1,
      title: "Introdução ao câmbio",
      summary: "Mercado cambial, divisas e regimes de taxa de câmbio.",
      minutes: 12,
      xp: 40,
      status: "concluido",
      stars: 3,
      href: "/v2/leitura",
    },
    {
      id: "n2",
      order: 2,
      title: "Balanço de pagamentos",
      summary: "Conta corrente, conta de capital e equilíbrio externo.",
      minutes: 15,
      xp: 40,
      status: "concluido",
      stars: 2,
      href: "/v2/leitura",
    },
    {
      id: "n3",
      order: 3,
      title: "Política monetária do BNA",
      summary: "Taxa de referência, reservas obrigatórias e canais de transmissão.",
      minutes: 14,
      xp: 40,
      status: "concluido",
      stars: 2,
      href: "/v2/leitura",
    },
    {
      id: "n4",
      order: 4,
      title: "Modelo Mundell-Fleming e taxa flutuante",
      summary: "Política fiscal e monetária numa economia aberta com câmbio flutuante.",
      minutes: 18,
      xp: 50,
      status: "ativo",
      href: "/v2/leitura",
    },
    {
      id: "n5",
      order: 5,
      title: "Inflação importada e pass-through",
      summary: "Como a depreciação do Kwanza chega aos preços da cesta básica.",
      minutes: 16,
      xp: 50,
      status: "bloqueado",
      href: "/v2/leitura",
    },
    {
      id: "n6",
      order: 6,
      title: "Reservas internacionais",
      summary: "Formação, gestão e papel amortecedor face a choques do petróleo.",
      minutes: 13,
      xp: 50,
      status: "bloqueado",
      href: "/v2/leitura",
    },
    {
      id: "n7",
      order: 7,
      title: "Casos práticos de exame",
      summary: "Resolução comentada das frequências dos últimos três anos.",
      minutes: 20,
      xp: 60,
      status: "bloqueado",
      href: "/v2/leitura",
    },
  ],
};

export const MOCK_ADAPTIVE: AdaptiveTrail = {
  subject: "Contabilidade II",
  course: "Economia",
  university: "UAN",
  initialAccuracy: 58,
  multiplier: 1.5,
  gaps: ["Lançamentos de amortização", "Provisões para créditos de cobrança duvidosa"],
  strengths: ["Balancete de verificação (100% de acerto)"],
  steps: [
    {
      id: "s1",
      kind: "reforco",
      title: "Quotas constantes e degressivas",
      summary:
        "Resumo de 4 minutos com as fórmulas mais cobradas nos exames da UAN e do ISAF, e o cálculo do valor contabilístico.",
      minutes: 4,
      baseXp: 50,
      dataMb: 0.2,
      failureRate: 42,
      status: "disponivel",
      href: "/v2/leitura",
    },
    {
      id: "s2",
      kind: "simulado",
      title: "Oito casos práticos de amortização",
      summary: "Problemas retirados das frequências dos últimos três anos, com resolução comentada.",
      minutes: 15,
      baseXp: 100,
      dataMb: 0.4,
      status: "bloqueado",
      href: "/v2/desafio",
    },
    {
      id: "s3",
      kind: "checkpoint",
      title: "Reavaliação diagnóstica",
      summary: "Cinco perguntas para confirmar que a lacuna ficou resolvida antes de voltares à trilha regular.",
      minutes: 6,
      baseXp: 150,
      dataMb: 0.1,
      badge: "Mestre das amortizações",
      status: "bloqueado",
      href: "/v2/desafio",
    },
  ],
};
