import type { ReviewQueue } from "./types";

export const MOCK_REVIEW: ReviewQueue = {
  multiplier: 2,
  sessionMinutes: 5,
  masteredCount: 45,
  items: [
    {
      id: "r1",
      subject: "Macroeconomia I",
      university: "UAN",
      topic: "Mundell-Fleming",
      question:
        "Qual é a consequência de uma política monetária expansionista com câmbio fixo e mobilidade perfeita de capitais?",
      chosenAnswer: "A taxa de juro cai de forma permanente e o produto aumenta bastante.",
      correctAnswer: "A política monetária é ineficaz para alterar o produto: há drenagem de reservas.",
      rationale:
        "Para sustentar a paridade, o banco central vende divisas e retira da economia a liquidez que tinha acabado de emitir.",
      attempts: 1,
      lastMissedDaysAgo: 3,
      level: 1,
      bucket: "hoje",
      xp: 10,
    },
    {
      id: "r2",
      subject: "Direito Fiscal",
      university: "UCAN",
      topic: "Código Geral Tributário",
      question: "Qual é o prazo para impugnação judicial da liquidação do Imposto Industrial?",
      chosenAnswer: "30 dias a contar da data da liquidação.",
      correctAnswer: "90 dias a contar do termo do prazo de pagamento voluntário.",
      rationale:
        "O prazo conta-se do fim do pagamento voluntário, e não da liquidação. É a troca mais comum nesta matéria.",
      attempts: 2,
      lastMissedDaysAgo: 7,
      level: 2,
      bucket: "hoje",
      xp: 10,
    },
    {
      id: "r3",
      subject: "Contabilidade Geral",
      university: "ISAF",
      topic: "Plano Geral de Contabilidade",
      question: "Como se regista uma provisão para créditos de cobrança duvidosa?",
      chosenAnswer: "Débito em proveitos e crédito em clientes.",
      correctAnswer: "Débito em custos do exercício e crédito na conta de provisões acumuladas.",
      rationale: "A provisão é um custo estimado do período; a conta de clientes não é creditada diretamente.",
      attempts: 1,
      lastMissedDaysAgo: 2,
      level: 1,
      bucket: "hoje",
      xp: 10,
    },
    {
      id: "r4",
      subject: "Macroeconomia I",
      university: "UAN",
      topic: "Balanço de pagamentos",
      question: "As remessas de emigrantes entram em que conta do balanço de pagamentos?",
      chosenAnswer: "Conta de capital.",
      correctAnswer: "Conta corrente, no rendimento secundário.",
      rationale: "A conta de capital regista transferências de capital, não rendimentos correntes sem contrapartida.",
      attempts: 1,
      lastMissedDaysAgo: 5,
      level: 2,
      bucket: "3dias",
      xp: 10,
    },
    {
      id: "r5",
      subject: "Estatística I",
      university: "UAN",
      topic: "Inferência",
      question: "O que significa um intervalo de confiança de 95%?",
      chosenAnswer: "Há 95% de probabilidade de o parâmetro estar neste intervalo.",
      correctAnswer: "Em 95% das amostras possíveis, o intervalo construído assim conteria o parâmetro.",
      rationale: "A probabilidade está no procedimento de amostragem, não no parâmetro, que é fixo.",
      attempts: 3,
      lastMissedDaysAgo: 12,
      level: 3,
      bucket: "7dias",
      xp: 10,
    },
  ],
};
